### ISSUE TITLE
Actividad 3_Cuadro comparativo

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Jaczibeth#1]
Jaczibeth 1bs
![CUADRO COMPARATIVO_JACZIBETH_IBS](https://user-images.githubusercontent.com/112178026/188515344-f31b0de7-cc21-49e4-8733-e942644608ef.jpg)

**Comment by 11042002** [comment]
Tu calificación es de: 19

**Comment by josealfredo79** [comment]
Muy bien hecho felicidades...
